name: Deploy Docs

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/test-docs.yml
  publish:
    needs: test
    uses: ./.github/workflows/publish-docs.yml
